package com.crowdar.examples.constants;

public class AddEntryConstants {

    public static final String LOCATOR_ADD_ENTRY_TOOLBAR_INITIAL_TITLE = "xpath://android.widget.TextView[@content-desc=\"Add entry\"]";
    public static final String LOCATOR_ADD_ENTRY_TOOLBAR_MANUAL_TITLE = "xpath://android.widget.TextView[@content-desc=\"Manual\"]";
    public static final String LOCATOR_HOURS_INPUT = "xpath:/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.NumberPicker[1]/android.widget.EditText";
    public static final String LOCATOR_HOURS_NEXT_BUTTON = "xpath:/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.NumberPicker[1]/android.widget.Button[2]";
    public static final String LOCATOR_MINUTES_INPUT = "xpath:/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.NumberPicker[2]/android.widget.EditText";
    public static final String LOCATOR_MINUTES_NEXT_BUTTON = "xpath:/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.NumberPicker[2]/android.widget.Button[2]";
    public static final String MESSAGE_VIEW_NOT_DISPLAYED = "Add Entry page is not displayed.";
    public static final String LOCATOR_TITLE_INPUT = "id:time_entry_description_input";
    public static final String LOCATOR_PROJECT_FIELD = "id:timeentry_project_section";
    public static final String LOCATOR_PROJECTS_SECTION_FIRST = "xpath:/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[1]/androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]/android.view.ViewGroup/android.widget.TextView";
    public static final String LOCATOR_PROJECT = "xpath://android.widget.TextView[@text='";
    public static final String LOCATOR_SELECTED_PROJECT = "id:timeentry_selected_project";
    public static final String LOCATOR_SAVE_BUTTON = "xpath://android.widget.Button[@text='SAVE']";
    public static final String LOCATOR_LAST_ITEM_TIME = "xpath:/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGroup/android.widget.TextView[1]";
    public static final String LOCATOR_LAST_ITEM_TITLE = "xpath:/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGroup/android.widget.TextView[2]";
    public static final String LOCATOR_LAST_ITEM_PROJECT = "xpath:/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/androidx.drawerlayout.widget.DrawerLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup[1]/android.view.ViewGroup/androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.widget.TextView";
    public static final String LOCATOR_LAST_ITEM_MENU = "xpath:(//android.widget.ImageView[@content-desc=\"Button more on time entry\"])[1]";
    public static final String LOCATOR_DELETE_BUTTON = "xpath://android.widget.TextView[@text='Delete']";
}
